### ISSUE TITLE
NetConnection.Call.Failed not emitted when trying to connect to server and there is no internet conncetion 

### ISSUE THREAD

**Issue by lighthousemobileapps** [shogo4405/HaishinKit.dart#65]
### Describe the bug

When a user has no internet connection and  attempts to connect to the rtmp server, there is no connection event emitted to the flutter side of the application.
However, the following error is emitted on the java side:

 java.net.ConnectException: failed to connect to "example-IP" (port 1935) from /:: (port 0): connect failed: ENETUNREACH (Network is unreachable)  

From my understanding, the connection event "NetConnection.Call.Failed" should be emitted and from that we can inform the user manually that they have a connectivity issue on their side.

### To Reproduce

- Run example app Example2
- Turn off all internet connections on android device
- Try to connect to a working RTMP server
- See Java exception java.net.ConnectException: failed to connect to in the logs

### Expected behavior

To receive the connection event NetConnection.Call.Failed

### Version

haishin_kit version 0.13.0

### Smartphone info.

Google Pixel 7 Pro
Android version 14

### Relevant log output

```shell
onnect failed: ENETUNREACH (Network is unreachable) does not 
[        ] W/NetSocketImpl( 1122): 	at libcore.io.IoBridge.connect(IoBridge.java:187)
[        ] W/NetSocketImpl( 1122): 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
[        ] W/NetSocketImpl( 1122): 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
[        ] W/NetSocketImpl( 1122): 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
[        ] W/NetSocketImpl( 1122): 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
[        ] W/NetSocketImpl( 1122): 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
[        ] W/NetSocketImpl( 1122): 	at java.net.Socket.connect(Socket.java:646)
[        ] W/NetSocketImpl( 1122): 	at java.net.Socket.connect(Socket.java:595)
[        ] W/NetSocketImpl( 1122): 	at java.net.Socket.<init>(Socket.java:475)
[        ] W/NetSocketImpl( 1122): 	at java.net.Socket.<init>(Socket.java:243)
[        ] W/NetSocketImpl( 1122): 	at com.haishinkit.net.NetSocketImpl.createSocket(NetSocketImpl.kt:203)
[        ] W/NetSocketImpl( 1122): 	at com.haishinkit.net.NetSocketImpl.doConnection(NetSocketImpl.kt:165)
[        ] W/NetSocketImpl( 1122): 	at com.haishinkit.net.NetSocketImpl.access$doConnection(NetSocketImpl.kt:21)
[        ] W/NetSocketImpl( 1122): 	at com.haishinkit.net.NetSocketImpl$connect$1.invokeSuspend(NetSocketImpl.kt:64)
[        ] W/NetSocketImpl( 1122): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[        ] W/NetSocketImpl( 1122): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
[        ] W/NetSocketImpl( 1122): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
[        ] W/NetSocketImpl( 1122): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
[        ] W/NetSocketImpl( 1122): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
[        ] W/NetSocketImpl( 1122): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
[        ] W/NetSocketImpl( 1122): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
[        ] W/NetSocketImpl( 1122): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
[        ] W/NetSocketImpl( 1122): Caused by: android.system.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
```

**Comment by shogo4405** [comment]
The design is as follows:
1. If it cannot connect at all, it will dispatch Event.IO_ERROR.
1. If it connects to the RTMP server but fails the handshake or cannot connect for other reasons, it will dispatch:
Event.RTMP_STATUS with `NetConnection.Call.Failed`.

Therefore, in cases like the current example-IP scenario, the design is to dispatch the Event.IO_ERROR event.
